export const WORLD_X = 100000;
export const GROUND_LINE = innerHeight/4
export const FLOOR = innerHeight - GROUND_LINE;
export const VECTOR_LENGTH = 200;
export const VEL_DIV = 1.5;
export const GRAVITY = .3;
export const PARTICLE_LIFE =1000;
export const NUM_ARROWS = 10;
export const ARROW_TRAIL_TTL = 15;